from strategy import Strategy_Multiplier

################################################################################
NAME = '--'
ACTIVATION_INTERVAL = (-1, -0.6)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 1.425
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 0.7
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 0.5

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

minus_minus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                  SNAPSHOT_REFRESH_RATE,
                                  LATEST_SNAPSHOT_COUNT,
                                  TRADING_CONFIGURATION,
                                  PRUNING_CONFIGURATION,
                                  PROFIT_RETENTION_CONFIGURATION,
                                  CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = '-'
ACTIVATION_INTERVAL = (-0.6, -.2)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 1.225
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 0.825
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 0.75

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

minus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                            SNAPSHOT_REFRESH_RATE,
                            LATEST_SNAPSHOT_COUNT,
                            TRADING_CONFIGURATION,
                            PRUNING_CONFIGURATION,
                            PROFIT_RETENTION_CONFIGURATION,
                            CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = '='
ACTIVATION_INTERVAL = (-0.2, 0.2)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 1
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 1
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1  # seconds

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

equals = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                             SNAPSHOT_REFRESH_RATE,
                             LATEST_SNAPSHOT_COUNT,
                             TRADING_CONFIGURATION,
                             PRUNING_CONFIGURATION,
                             PROFIT_RETENTION_CONFIGURATION,
                             CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = '+'
ACTIVATION_INTERVAL = (0.2, 0.6)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 0.775
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 1.1
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1.1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

plus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                           SNAPSHOT_REFRESH_RATE,
                           LATEST_SNAPSHOT_COUNT,
                           TRADING_CONFIGURATION,
                           PRUNING_CONFIGURATION,
                           PROFIT_RETENTION_CONFIGURATION,
                           CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = '++'
ACTIVATION_INTERVAL = (0.6, 1)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 0.625
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 1.2
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1.4

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

plus_plus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                SNAPSHOT_REFRESH_RATE,
                                LATEST_SNAPSHOT_COUNT,
                                TRADING_CONFIGURATION,
                                PRUNING_CONFIGURATION,
                                PROFIT_RETENTION_CONFIGURATION,
                                CONFIRMATION_CONFIGURATION)
################################################################################
