from strategy import Strategy_Multiplier

################################################################################
NAME = 'BEAR--'
ACTIVATION_INTERVAL = (0, 0.5 / 6)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 0.9
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 1.2
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 0.8
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1.75
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 0.5
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m2_bear_minus_minus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                          SNAPSHOT_REFRESH_RATE,
                                          LATEST_SNAPSHOT_COUNT,
                                          TRADING_CONFIGURATION,
                                          PRUNING_CONFIGURATION,
                                          PROFIT_RETENTION_CONFIGURATION,
                                          CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BEAR-'
ACTIVATION_INTERVAL = (0.5 / 6, 1 / 6)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 0.9
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 1.155
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 0.9
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m2_bear_minus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                    SNAPSHOT_REFRESH_RATE,
                                    LATEST_SNAPSHOT_COUNT,
                                    TRADING_CONFIGURATION,
                                    PRUNING_CONFIGURATION,
                                    PROFIT_RETENTION_CONFIGURATION,
                                    CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BEAR'
ACTIVATION_INTERVAL = (1 / 6, 2 / 6)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 0.95
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 1.125
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 0.95
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1  # seconds

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m2_bear = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                              SNAPSHOT_REFRESH_RATE,
                              LATEST_SNAPSHOT_COUNT,
                              TRADING_CONFIGURATION,
                              PRUNING_CONFIGURATION,
                              PROFIT_RETENTION_CONFIGURATION,
                              CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BEAR+'
ACTIVATION_INTERVAL = (2 / 6, 3 / 6)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 0.99
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 1.01
FC_REBOUND_RATIO = 1.5

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 0.99
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m2_bear_plus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                   SNAPSHOT_REFRESH_RATE,
                                   LATEST_SNAPSHOT_COUNT,
                                   TRADING_CONFIGURATION,
                                   PRUNING_CONFIGURATION,
                                   PROFIT_RETENTION_CONFIGURATION,
                                   CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BULL-'
ACTIVATION_INTERVAL = (3 / 6, 4 / 6)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1.01
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 0.945
FC_REBOUND_RATIO = 1.25

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 1.01
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m2_bull_minus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                    SNAPSHOT_REFRESH_RATE,
                                    LATEST_SNAPSHOT_COUNT,
                                    TRADING_CONFIGURATION,
                                    PRUNING_CONFIGURATION,
                                    PROFIT_RETENTION_CONFIGURATION,
                                    CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BULL'
ACTIVATION_INTERVAL = (4 / 6, 5 / 6)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1
CF_REBOUND_RATIO = 1.02

FC_DELTA_THRESHOLD = 0.945
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 1.05
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m2_bull = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                              SNAPSHOT_REFRESH_RATE,
                              LATEST_SNAPSHOT_COUNT,
                              TRADING_CONFIGURATION,
                              PRUNING_CONFIGURATION,
                              PROFIT_RETENTION_CONFIGURATION,
                              CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BULL+'
ACTIVATION_INTERVAL = (5 / 6, 5.5 / 6)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1
CF_REBOUND_RATIO = 1.1

FC_DELTA_THRESHOLD = 0.925
FC_REBOUND_RATIO = 1.15

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 1
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m2_bull_plus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                   SNAPSHOT_REFRESH_RATE,
                                   LATEST_SNAPSHOT_COUNT,
                                   TRADING_CONFIGURATION,
                                   PRUNING_CONFIGURATION,
                                   PROFIT_RETENTION_CONFIGURATION,
                                   CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BULL++'
ACTIVATION_INTERVAL = (5.5 / 6, 1)

SNAPSHOT_REFRESH_RATE = 1
LATEST_SNAPSHOT_COUNT = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1
CF_REBOUND_RATIO = 1.1

FC_DELTA_THRESHOLD = 0.9
FC_REBOUND_RATIO = 1.35

REBOUND_WAIT_TIME = 1
TRADING_COOLDOWN_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 1.2
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1.2

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME,
    'TRADING_COOLDOWN_TIME': TRADING_COOLDOWN_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m2_bull_plus_plus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                        SNAPSHOT_REFRESH_RATE,
                                        LATEST_SNAPSHOT_COUNT,
                                        TRADING_CONFIGURATION,
                                        PRUNING_CONFIGURATION,
                                        PROFIT_RETENTION_CONFIGURATION,
                                        CONFIRMATION_CONFIGURATION)
################################################################################
