from strategy import Strategy_Multiplier

################################################################################
NAME = 'BEAR-'
ACTIVATION_INTERVAL = (0, 1 / 6)

SNAPSHOT_REFRESH_RATE = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 0.9
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 1.3
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 0.9
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m1_bear_minus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                    SNAPSHOT_REFRESH_RATE,
                                    TRADING_CONFIGURATION,
                                    PRUNING_CONFIGURATION,
                                    PROFIT_RETENTION_CONFIGURATION,
                                    CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BEAR'
ACTIVATION_INTERVAL = (1 / 6, 2 / 6)

SNAPSHOT_REFRESH_RATE = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 0.95
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 1.05
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 0.95
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1  # seconds

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m1_bear = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                              SNAPSHOT_REFRESH_RATE,
                              TRADING_CONFIGURATION,
                              PRUNING_CONFIGURATION,
                              PROFIT_RETENTION_CONFIGURATION,
                              CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BEAR+'
ACTIVATION_INTERVAL = (2 / 6, 3 / 6)

SNAPSHOT_REFRESH_RATE = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 0.99
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 1.01
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 0.99
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m1_bear_plus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                   SNAPSHOT_REFRESH_RATE,
                                   TRADING_CONFIGURATION,
                                   PRUNING_CONFIGURATION,
                                   PROFIT_RETENTION_CONFIGURATION,
                                   CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BULL-'
ACTIVATION_INTERVAL = (3 / 6, 4 / 6)

SNAPSHOT_REFRESH_RATE = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1.01
CF_REBOUND_RATIO = 1

FC_DELTA_THRESHOLD = 0.985
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 1.01
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m1_bull_minus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                    SNAPSHOT_REFRESH_RATE,
                                    TRADING_CONFIGURATION,
                                    PRUNING_CONFIGURATION,
                                    PROFIT_RETENTION_CONFIGURATION,
                                    CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BULL'
ACTIVATION_INTERVAL = (4 / 6, 5 / 6)

SNAPSHOT_REFRESH_RATE = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1
CF_REBOUND_RATIO = 1.02

FC_DELTA_THRESHOLD = 0.95
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 1.05
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m1_bull = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                              SNAPSHOT_REFRESH_RATE,
                              TRADING_CONFIGURATION,
                              PRUNING_CONFIGURATION,
                              PROFIT_RETENTION_CONFIGURATION,
                              CONFIRMATION_CONFIGURATION)
################################################################################

################################################################################
NAME = 'BULL+'
ACTIVATION_INTERVAL = (5 / 6, 1)

SNAPSHOT_REFRESH_RATE = 1

# Configure trading strategy
CF_DELTA_THRESHOLD = 1
CF_REBOUND_RATIO = 1.1

FC_DELTA_THRESHOLD = 0.9
FC_REBOUND_RATIO = 1

REBOUND_WAIT_TIME = 1

# Configure suspension strategy
SUSPENSION_THRESHOLD = 1
SUSPENSION_TIME = 1

# Configure profit retention strategy
PROFIT_RETENTION_ACTIVATION_POSITIVE = 1.1
PROFIT_RETENTION_ACTIVATION_NEGATIVE = 1

# Configure confirmation setting
BUY_CONFIRMATION_REPETITION = 1
BUY_CONFIRMATION_DELAY = 1

SELL_CONFIRMATION_REPETITION = 1
SELL_CONFIRMATION_DELAY = 1

IDENTITY_CONFIGURATION = {
    'NAME': NAME,
    'INTERVAL': ACTIVATION_INTERVAL
}

TRADING_CONFIGURATION = {
    'CF': (CF_DELTA_THRESHOLD, CF_REBOUND_RATIO),
    'FC': (FC_DELTA_THRESHOLD, FC_REBOUND_RATIO),
    'REBOUND_WAIT_TIME': REBOUND_WAIT_TIME}

PRUNING_CONFIGURATION = {
    'SNAPSHOT': (SUSPENSION_THRESHOLD, SUSPENSION_TIME)}

PROFIT_RETENTION_CONFIGURATION = (PROFIT_RETENTION_ACTIVATION_POSITIVE,
                                  PROFIT_RETENTION_ACTIVATION_NEGATIVE)

CONFIRMATION_CONFIGURATION = {
    'BUY': (BUY_CONFIRMATION_REPETITION, BUY_CONFIRMATION_DELAY),
    'SELL': (SELL_CONFIRMATION_REPETITION, SELL_CONFIRMATION_DELAY)}

m1_bull_plus = Strategy_Multiplier(IDENTITY_CONFIGURATION,
                                   SNAPSHOT_REFRESH_RATE,
                                   TRADING_CONFIGURATION,
                                   PRUNING_CONFIGURATION,
                                   PROFIT_RETENTION_CONFIGURATION,
                                   CONFIRMATION_CONFIGURATION)
################################################################################
